import pptxgen from 'pptxgenjs';

const pptx = new pptxgen();
pptx.layout = 'LAYOUT_WIDE';
pptx.author = 'LLDIKTI Wilayah III';
pptx.subject = 'Manual Book Modul Keuangan SIPITUNG';
pptx.title = 'Manual Book Modul Keuangan SIPITUNG';
pptx.company = 'LLDIKTI Wilayah III';
pptx.lang = 'id-ID';
pptx.theme = {
  headFontFace: 'Aptos Display',
  bodyFontFace: 'Aptos',
  lang: 'id-ID',
};
pptx.defineSlideMaster({
  title: 'MASTER',
  background: { color: 'F6F8FC' },
  objects: [
    { rect: { x: 0, y: 7.12, w: 13.333, h: 0.38, fill: { color: '102A43' }, line: { color: '102A43' } } },
    { text: { text: 'SIPITUNG  /  MODUL KEUANGAN', options: { x: 0.42, y: 7.2, w: 4.5, h: 0.14, fontFace: 'Aptos', fontSize: 8, color: 'B9C9DD', margin: 0 } } },
    { text: { text: 'LLDIKTI WILAYAH III', options: { x: 10.6, y: 7.2, w: 2.3, h: 0.14, fontFace: 'Aptos', fontSize: 8, color: 'B9C9DD', align: 'right', margin: 0 } } },
  ],
  slideNumber: { x: 12.94, y: 7.2, color: 'FFFFFF', fontFace: 'Aptos', fontSize: 8 },
});

const C = { navy: '102A43', blue: '1769AA', teal: '008C95', mint: 'DDF4F1', gold: 'F4B942', ink: '243B53', muted: '627D98', line: 'D9E2EC', bg: 'F6F8FC', white: 'FFFFFF', red: 'C05640', softBlue: 'E8F1FA', softGold: 'FFF4D6', softRed: 'FCE8E6' };
const W = 13.333;

function text(slide, value, x, y, w, h, opts = {}) {
  slide.addText(value, { x, y, w, h, margin: 0, breakLine: false, fit: 'shrink', fontFace: opts.fontFace || 'Aptos', fontSize: opts.fontSize || 14, color: opts.color || C.ink, bold: opts.bold || false, italic: opts.italic || false, align: opts.align || 'left', valign: opts.valign || 'mid', paraSpaceAfterPt: opts.paraSpaceAfterPt || 0, bullet: opts.bullet, ...opts });
}
function box(slide, x, y, w, h, fill = C.white, line = C.line, radius = 0.12) {
  slide.addShape(pptx.ShapeType.roundRect, { x, y, w, h, rectRadius: radius, fill: { color: fill }, line: { color: line, width: 1 } });
}
function line(slide, x, y, w, color = C.line, width = 1) { slide.addShape(pptx.ShapeType.line, { x, y, w, h: 0, line: { color, width } }); }
function pill(slide, label, x, y, w, fill, color = C.navy) { slide.addShape(pptx.ShapeType.roundRect, { x, y, w, h: 0.3, rectRadius: 0.15, fill: { color: fill }, line: { color: fill } }); text(slide, label, x, y + 0.01, w, 0.24, { fontSize: 8.5, color, bold: true, align: 'center' }); }
function header(slide, kicker, title, subtitle = '') { text(slide, kicker.toUpperCase(), 0.55, 0.35, 6.5, 0.22, { fontSize: 9, color: C.teal, bold: true, charSpacing: 1.2 }); text(slide, title, 0.55, 0.62, 12.2, 0.48, { fontSize: 24, color: C.navy, bold: true }); if (subtitle) text(slide, subtitle, 0.55, 1.13, 11.8, 0.3, { fontSize: 11, color: C.muted }); line(slide, 0.55, 1.52, 12.2, C.gold, 2.5); }
function note(slide, label, body, x, y, w, h, fill = C.softGold, accent = C.gold) { box(slide, x, y, w, h, fill, fill); slide.addShape(pptx.ShapeType.rect, { x, y, w: 0.08, h, fill: { color: accent }, line: { color: accent } }); text(slide, label.toUpperCase(), x + 0.22, y + 0.14, w - 0.4, 0.18, { fontSize: 8, color: C.muted, bold: true, charSpacing: 0.8 }); text(slide, body, x + 0.22, y + 0.37, w - 0.4, h - 0.48, { fontSize: 10.5, color: C.ink, valign: 'top' }); }
function placeholder(slide, title, x, y, w, h, caption = 'Masukkan screenshot halaman ini') { box(slide, x, y, w, h, 'EDF4FA', C.blue); slide.addShape(pptx.ShapeType.rect, { x, y, w, h: 0.38, fill: { color: C.blue }, line: { color: C.blue } }); text(slide, title, x + 0.16, y + 0.07, w - 0.3, 0.18, { fontSize: 9.5, color: C.white, bold: true }); slide.addShape(pptx.ShapeType.line, { x: x + 0.5, y: y + h / 2 + 0.1, w: w - 1, h: 0, line: { color: 'A8C7E3', width: 1, dash: 'dash' } }); slide.addShape(pptx.ShapeType.line, { x: x + w / 2, y: y + 0.72, w: 0, h: h - 1.1, line: { color: 'A8C7E3', width: 1, dash: 'dash' } }); text(slide, caption, x + 0.35, y + h / 2 - 0.18, w - 0.7, 0.45, { fontSize: 11, color: C.blue, italic: true, align: 'center' }); }
function bulletList(slide, items, x, y, w, h, opts = {}) { items.forEach((item, i) => { const yy = y + i * (opts.gap || 0.43); slide.addShape(pptx.ShapeType.ellipse, { x, y: yy + 0.1, w: 0.1, h: 0.1, fill: { color: opts.dot || C.teal }, line: { color: opts.dot || C.teal } }); text(slide, item, x + 0.22, yy, w - 0.22, opts.rowH || 0.3, { fontSize: opts.fontSize || 11, color: opts.color || C.ink, valign: 'top' }); }); }
function roleCard(slide, role, desc, x, y, color) { box(slide, x, y, 2.85, 1.2, C.white, C.line); slide.addShape(pptx.ShapeType.rect, { x, y, w: 2.85, h: 0.1, fill: { color }, line: { color } }); text(slide, role, x + 0.2, y + 0.22, 2.45, 0.25, { fontSize: 13, bold: true, color: C.navy }); text(slide, desc, x + 0.2, y + 0.56, 2.45, 0.4, { fontSize: 9.5, color: C.muted, valign: 'top' }); }
function section(title, subtitle, num, color = C.teal) { const s = pptx.addSlide(); s.background = { color: C.navy }; s.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: 0.36, h: 7.5, fill: { color }, line: { color } }); text(s, `BAGIAN ${num}`, 0.8, 1.1, 3, 0.28, { fontSize: 12, color: C.gold, bold: true, charSpacing: 1.2 }); text(s, title, 0.8, 1.55, 11.5, 1.1, { fontSize: 34, color: C.white, bold: true }); text(s, subtitle, 0.8, 2.85, 10.8, 0.5, { fontSize: 15, color: 'C4D4E7' }); line(s, 0.8, 3.65, 11.8, C.gold, 2); text(s, 'SIPITUNG  /  MODUL KEUANGAN', 0.8, 6.86, 5, 0.2, { fontSize: 9, color: '9FB3C8', bold: true, charSpacing: 0.8 }); return s; }
function addSlide(title, kicker, subtitle = '') { const s = pptx.addSlide('MASTER'); header(s, kicker, title, subtitle); return s; }

// Cover
{ const s = pptx.addSlide(); s.background = { color: C.navy }; s.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: 4.3, h: 7.5, fill: { color: '0B1F33' }, line: { color: '0B1F33' } }); s.addShape(pptx.ShapeType.rect, { x: 4.3, y: 0, w: 0.08, h: 7.5, fill: { color: C.gold }, line: { color: C.gold } }); box(s, 0.55, 0.62, 3.2, 1.15, '173B59', C.teal); text(s, 'LOGO\nLLDIKTI WILAYAH III', 0.7, 0.82, 2.9, 0.72, { fontSize: 15, color: C.white, bold: true, align: 'center' }); text(s, 'PETUNJUK PENGGUNAAN', 0.55, 2.35, 3.2, 0.2, { fontSize: 9, color: C.gold, bold: true, charSpacing: 1.3 }); text(s, 'Modul Keuangan\nSIPITUNG', 0.55, 2.7, 3.2, 1.1, { fontSize: 23, color: C.white, bold: true }); line(s, 0.55, 4.15, 3.1, C.gold, 2); text(s, 'Manual book untuk seluruh pengguna\nSuper Admin, PUMK, KA.TIM, PIC Keuangan,\nPimpinan, PPK, dan Bendahara', 0.55, 4.45, 3.15, 1, { fontSize: 11, color: 'C4D4E7', valign: 'top' }); text(s, 'LLDIKTI WILAYAH III  |  2026', 0.55, 6.83, 3.2, 0.2, { fontSize: 9, color: '9FB3C8' }); text(s, 'SIPITUNG', 5.0, 0.82, 7.5, 0.75, { fontSize: 44, color: C.white, bold: true }); text(s, 'Sistem Informasi Perencanaan & Kinerja', 5.03, 1.62, 7.5, 0.3, { fontSize: 16, color: C.gold, bold: true }); text(s, 'Alur digital pengelolaan Permohonan Dana Kegiatan', 5.03, 2.45, 7.3, 0.45, { fontSize: 20, color: C.white, bold: true }); text(s, 'Dari master data dan RKA-K/L hingga pencairan, bukti pembayaran, dan LPJ.', 5.03, 3.08, 7.1, 0.38, { fontSize: 13, color: 'C4D4E7' }); const labels = [['01', 'Master data'], ['02', 'Permohonan'], ['03', 'Persetujuan'], ['04', 'Realisasi']]; labels.forEach((v, i) => { const x = 5.03 + i * 1.85; box(s, x, 4.25, 1.58, 1.05, i === 3 ? C.teal : '173B59', i === 3 ? C.teal : '315B80'); text(s, v[0], x + 0.15, 4.43, 0.42, 0.24, { fontSize: 12, color: C.gold, bold: true }); text(s, v[1], x + 0.15, 4.76, 1.2, 0.3, { fontSize: 10.5, color: C.white, bold: true }); }); }

// Contents
{ const s = addSlide('Panduan dalam satu alur', '01  /  ORIENTASI', 'Gunakan daftar ini untuk menemukan bagian yang sesuai dengan peran Anda.'); const items = [['A', 'Orientasi', 'Tujuan, aktor, dan alur umum'], ['B', 'Master Data', 'Tahun anggaran, pengguna, pegawai, tim kerja'], ['C', 'Master Anggaran', 'RKA-K/L dan struktur rincian biaya'], ['D', 'Permohonan Dana', 'Pengajuan, dokumen, biaya, dan nominatif'], ['E', 'Persetujuan', 'KA.TIM, PIC Keuangan, Pimpinan, dan PPK'], ['F', 'Pencairan & LPJ', 'Bendahara, bukti bayar, dan pertanggungjawaban']]; items.forEach((v, i) => { const x = 0.65 + (i % 2) * 6.15; const y = 1.9 + Math.floor(i / 2) * 1.35; box(s, x, y, 5.65, 1.05, C.white, C.line); pill(s, v[0], x + 0.22, y + 0.28, 0.42, i < 2 ? C.mint : i < 4 ? C.softBlue : C.softGold, C.navy); text(s, v[1], x + 0.84, y + 0.2, 4.45, 0.25, { fontSize: 14, color: C.navy, bold: true }); text(s, v[2], x + 0.84, y + 0.55, 4.45, 0.22, { fontSize: 10.5, color: C.muted }); }); }

// Orientation
{ const s = addSlide('Apa yang dikelola SIPITUNG?', '02  /  ORIENTASI', 'Modul Keuangan menghubungkan anggaran, permohonan, persetujuan, pencairan, dan pertanggungjawaban dalam satu jejak proses.'); note(s, 'Tujuan', 'Membantu setiap pengguna memahami langkah dan batas kewenangannya sebelum memproses data keuangan.', 0.65, 1.9, 3.75, 1.45, C.mint, C.teal); note(s, 'Prinsip', 'Data dimasukkan sekali, diperiksa berjenjang, dan tersimpan sebagai riwayat proses.', 4.8, 1.9, 3.75, 1.45, C.softBlue, C.blue); note(s, 'Catatan', 'Gunakan data yang sah dan sesuai dokumen RKA-K/L. Hindari mengunggah data yang tidak diperlukan.', 8.95, 1.9, 3.75, 1.45, C.softGold, C.gold); text(s, 'Alur utama', 0.65, 4.1, 2.2, 0.25, { fontSize: 14, color: C.navy, bold: true }); const flow = ['Master data', 'RKA-K/L', 'Permohonan', 'Verifikasi', 'Persetujuan', 'Pencairan', 'LPJ']; flow.forEach((v, i) => { const x = 0.65 + i * 1.73; box(s, x, 4.62, 1.42, 0.65, i === 6 ? C.teal : C.white, i === 6 ? C.teal : C.line); text(s, v, x + 0.08, 4.8, 1.26, 0.2, { fontSize: 9.5, color: i === 6 ? C.white : C.navy, bold: true, align: 'center' }); if (i < flow.length - 1) text(s, '›', x + 1.48, 4.78, 0.2, 0.24, { fontSize: 18, color: C.gold, bold: true, align: 'center' }); }); }

// Roles
{ const s = addSlide('Siapa melakukan apa?', '03  /  ORIENTASI', 'Hak akses menentukan menu yang terlihat dan tindakan yang dapat dilakukan.'); const roles = [['Super Admin', 'Menyiapkan data dasar dan master anggaran', C.blue], ['PUMK', 'Membuat dan mengajukan permohonan', C.teal], ['KA.TIM', 'Memeriksa permohonan tim kerja', C.gold], ['PIC Keuangan', 'Memverifikasi biaya dan dokumen', C.blue], ['Pimpinan / PPK', 'Memberikan persetujuan berjenjang', C.teal], ['Bendahara', 'Mencairkan dan mencatat bukti pembayaran', C.gold]]; roles.forEach((r, i) => roleCard(s, r[0], r[1], 0.65 + (i % 3) * 4.15, 1.9 + Math.floor(i / 3) * 1.6, r[2])); note(s, 'Akses', 'Bila menu tidak muncul, periksa role dan status pengguna. Hubungi Super Admin untuk perubahan akses.', 0.65, 5.45, 11.95, 0.75, C.softBlue, C.blue); }

// Sections
section('Master Data', 'Menyiapkan referensi yang menjadi fondasi seluruh transaksi keuangan.', 'A', C.teal);
{ const s = addSlide('Login dan dashboard', '04  /  MASTER DATA', 'Mulai setiap proses dengan akun sesuai peran.'); placeholder(s, 'Screenshot halaman login', 0.65, 1.9, 6.7, 4.45); box(s, 7.75, 1.9, 4.85, 2.05, C.white, C.line); text(s, 'Langkah singkat', 8.05, 2.18, 4.2, 0.25, { fontSize: 14, bold: true, color: C.navy }); bulletList(s, ['Buka alamat aplikasi SIPITUNG.', 'Masukkan username dan password.', 'Klik Masuk, lalu pastikan dashboard sesuai role.'], 8.05, 2.62, 4.1, 1.0); note(s, 'Keamanan', 'Jangan membagikan kredensial. Logout setelah selesai menggunakan aplikasi.', 7.75, 4.25, 4.85, 1.2, C.softGold, C.gold); }
{ const s = addSlide('Tahun anggaran', '05  /  MASTER DATA', 'Tahun anggaran aktif menjadi konteks data yang digunakan pada proses berikutnya.'); placeholder(s, 'Screenshot menu tahun anggaran', 0.65, 1.85, 7.1, 4.55); box(s, 8.05, 1.85, 4.55, 2.55, C.white, C.line); text(s, 'Prosedur', 8.35, 2.13, 3.8, 0.25, { fontSize: 14, color: C.navy, bold: true }); bulletList(s, ['Buka Data Master → Tahun Anggaran.', 'Tambah tahun dan label tahun anggaran.', 'Tentukan tahun aktif/default.', 'Pastikan status aktif sebelum input transaksi.'], 8.35, 2.55, 3.85, 1.35); note(s, 'Validasi', 'Jangan membuat permohonan sebelum tahun anggaran aktif tersedia.', 8.05, 4.7, 4.55, 1.0, C.mint, C.teal); }
{ const s = addSlide('Pengguna, pegawai, dan tim kerja', '06  /  MASTER DATA', 'Tiga referensi ini menentukan siapa yang dapat masuk, menerima dana, dan memproses permohonan.'); [['Pengguna', 'Username, role, status aktif, dan tim kerja.'], ['Referensi pegawai', 'Identitas, status kepegawaian, rekening, bank, dan pajak.'], ['Tim kerja', 'Kode, nama, ketua tim, dan status aktif.']].forEach((v, i) => { const x = 0.65 + i * 4.15; box(s, x, 1.85, 3.75, 1.18, i === 0 ? C.softBlue : i === 1 ? C.mint : C.softGold, C.line); text(s, v[0], x + 0.22, 2.08, 3.25, 0.25, { fontSize: 14, bold: true, color: C.navy }); text(s, v[1], x + 0.22, 2.43, 3.2, 0.35, { fontSize: 10, color: C.ink, valign: 'top' }); }); placeholder(s, 'Screenshot daftar master data', 0.65, 3.55, 7.1, 2.8); note(s, 'Perlindungan data', 'Saat membuat dokumentasi, samarkan NIK, NPWP, nomor rekening, email, dan nomor telepon.', 8.05, 3.55, 4.55, 1.15, C.softRed, C.red); note(s, 'Urutan', 'Siapkan pegawai dan tim kerja sebelum PUMK mengisi nominatif.', 8.05, 4.95, 4.55, 1.15, C.softBlue, C.blue); }

section('Master Anggaran', 'Memasukkan dan memastikan data RKA-K/L siap dipakai sebagai sumber pilihan permohonan.', 'B', C.blue);
{ const s = addSlide('Impor master anggaran', '07  /  MASTER ANGGARAN', 'Data RKA-K/L digunakan sebagai dasar struktur anggaran pada SIPITUNG.'); placeholder(s, 'Screenshot impor master anggaran', 0.65, 1.85, 7.1, 4.55); box(s, 8.05, 1.85, 4.55, 2.65, C.white, C.line); text(s, 'Prosedur Super Admin', 8.35, 2.13, 3.85, 0.25, { fontSize: 14, color: C.navy, bold: true }); bulletList(s, ['Buka Keuangan → Master Anggaran.', 'Pilih tahun anggaran aktif.', 'Unggah berkas master anggaran.', 'Periksa pratinjau lalu konfirmasi impor.'], 8.35, 2.55, 3.85, 1.35); note(s, 'Penting', 'Gunakan RKA-K/L yang menjadi dasar input SIPITUNG. Pastikan tahun dan struktur datanya sesuai.', 8.05, 4.85, 4.55, 1.0, C.softGold, C.gold); }
{ const s = addSlide('Memahami hierarki anggaran', '08  /  MASTER ANGGARAN', 'Pilihan pada form permohonan mengikuti urutan hierarki dari umum ke rinci.'); const h = ['Program', 'Sasaran', 'KRO', 'RO', 'Komponen', 'Kegiatan', 'Subkegiatan', 'Rincian biaya']; h.forEach((v, i) => { const x = 0.65 + (i % 4) * 3.05; const y = 1.9 + Math.floor(i / 4) * 1.55; box(s, x, y, 2.7, 0.95, i < 4 ? C.softBlue : C.mint, C.line); text(s, String(i + 1).padStart(2, '0'), x + 0.2, y + 0.2, 0.4, 0.25, { fontSize: 12, color: C.teal, bold: true }); text(s, v, x + 0.72, y + 0.2, 1.75, 0.25, { fontSize: 13, color: C.navy, bold: true }); text(s, i < 4 ? 'Level strategis' : 'Level operasional', x + 0.72, y + 0.53, 1.75, 0.18, { fontSize: 9, color: C.muted }); }); placeholder(s, 'Screenshot struktur anggaran', 0.65, 5.25, 7.1, 1.15, 'Masukkan screenshot daftar program / rincian biaya'); note(s, 'Konsistensi', 'Jangan mengubah master anggaran ketika masih digunakan oleh permohonan aktif.', 8.05, 5.25, 4.55, 1.15, C.softGold, C.gold); }
{ const s = addSlide('Pemeriksaan pagu dan sisa anggaran', '09  /  MASTER ANGGARAN', 'SIPITUNG menampilkan penggunaan anggaran untuk membantu mencegah permohonan melebihi pagu.'); placeholder(s, 'Screenshot pagu dan sisa anggaran', 0.65, 1.9, 7.1, 4.45); ['Pagu total', 'Terpakai', 'Sisa anggaran'].forEach((v, i) => { const x = 8.05; const y = 1.9 + i * 0.95; box(s, x, y, 4.55, 0.7, i === 2 ? C.mint : C.white, C.line); text(s, v, x + 0.25, y + 0.15, 2.2, 0.2, { fontSize: 11, color: C.muted }); text(s, 'Rp —', x + 2.7, y + 0.15, 1.5, 0.2, { fontSize: 13, color: C.navy, bold: true, align: 'right' }); }); note(s, 'Checklist', 'Periksa kode akun, nama item, satuan, harga satuan, status aktif, dan sisa pagu.', 8.05, 4.95, 4.55, 1.2, C.softBlue, C.blue); }

section('Permohonan Dana', 'Membuat pengajuan kegiatan secara lengkap, terukur, dan siap diperiksa.', 'C', C.teal);
{ const s = addSlide('Membuat draft permohonan', '10  /  PERMOHONAN DANA', 'PUMK memulai permohonan dengan memilih konteks anggaran dan judul pekerjaan.'); placeholder(s, 'Screenshot form buat permohonan', 0.65, 1.85, 7.1, 4.55); box(s, 8.05, 1.85, 4.55, 2.7, C.white, C.line); text(s, 'Langkah PUMK', 8.35, 2.12, 3.8, 0.25, { fontSize: 14, color: C.navy, bold: true }); bulletList(s, ['Buka Permohonan Dana → Buat Permohonan.', 'Pilih Program sampai Kegiatan.', 'Isi judul pekerjaan/keperluan.', 'Klik Simpan untuk membuat draft.'], 8.35, 2.55, 3.85, 1.4); note(s, 'Hasil', 'Nomor permohonan dibuat otomatis dan status awal adalah Draft.', 8.05, 4.85, 4.55, 1.0, C.mint, C.teal); }
{ const s = addSlide('Mengisi kegiatan, waktu, dan penanggung jawab', '11  /  PERMOHONAN DANA', 'Lengkapi konteks kegiatan sebelum mengisi rincian biaya.'); placeholder(s, 'Screenshot tahap Kegiatan dan Waktu & PJ', 0.65, 1.85, 7.1, 4.55); box(s, 8.05, 1.85, 4.55, 2.6, C.white, C.line); text(s, 'Data yang diisi', 8.35, 2.12, 3.8, 0.25, { fontSize: 14, color: C.navy, bold: true }); bulletList(s, ['Judul pekerjaan dan keperluan.', 'Tanggal mulai dan selesai.', 'Jam pelaksanaan dan tempat.', 'Tanggal pertanggungjawaban.', 'KA.TIM dan PIC Keuangan bila tersedia.'], 8.35, 2.55, 3.85, 1.6); note(s, 'Periksa ulang', 'Tanggal kegiatan harus konsisten dengan dokumen pendukung dan rincian perjalanan.', 8.05, 4.8, 4.55, 1.05, C.softGold, C.gold); }
{ const s = addSlide('Mengunggah dokumen pendukung', '12  /  PERMOHONAN DANA', 'Dokumen membantu pemeriksa memvalidasi kebutuhan, waktu, dan besaran permohonan.'); placeholder(s, 'Screenshot tahap Dokumen', 0.65, 1.85, 7.1, 4.55); text(s, 'Alur unggah', 8.05, 1.9, 4.2, 0.25, { fontSize: 14, color: C.navy, bold: true }); [['01', 'Pilih jenis dokumen'], ['02', 'Pilih file yang benar'], ['03', 'Unggah dan tunggu status berhasil'], ['04', 'Hapus/ganti jika ada kesalahan']].forEach((v, i) => { const y = 2.35 + i * 0.7; pill(s, v[0], 8.05, y, 0.42, C.mint, C.teal); text(s, v[1], 8.7, y + 0.04, 3.75, 0.22, { fontSize: 10.5, color: C.ink }); }); note(s, 'Format', 'Gunakan format dan ukuran file sesuai validasi yang tampil pada aplikasi.', 8.05, 5.35, 4.55, 0.85, C.softBlue, C.blue); }
{ const s = addSlide('Mengisi rincian biaya', '13  /  PERMOHONAN DANA', 'Rincian biaya harus bersumber dari item anggaran yang tersedia dan tidak melebihi sisa pagu.'); placeholder(s, 'Screenshot tahap Rincian Biaya', 0.65, 1.8, 7.1, 4.65); box(s, 8.05, 1.8, 4.55, 2.9, C.white, C.line); text(s, 'Yang perlu diperiksa', 8.35, 2.08, 3.8, 0.25, { fontSize: 14, color: C.navy, bold: true }); bulletList(s, ['Subkegiatan dan kode akun.', 'Nama item dan satuan.', 'Volume yang diminta.', 'Harga satuan dan jumlah permintaan.', 'Pagu, terpakai, dan sisa anggaran.'], 8.35, 2.52, 3.85, 1.55); note(s, 'Validasi otomatis', 'Jika total melebihi sisa anggaran, perbaiki volume atau pilih rincian biaya yang sesuai.', 8.05, 5.0, 4.55, 1.05, C.softRed, C.red); }
{ const s = addSlide('Mengisi daftar nominatif', '14  /  PERMOHONAN DANA', 'Gunakan nominatif untuk item honorarium atau perjalanan dinas yang memerlukan penerima.'); placeholder(s, 'Screenshot form nominatif', 0.65, 1.8, 7.1, 4.65); text(s, 'Data penerima', 8.05, 1.85, 4.2, 0.25, { fontSize: 14, color: C.navy, bold: true }); bulletList(s, ['Pilih pegawai dari referensi nama.', 'Periksa identitas dan rekening.', 'Isi jabatan, volume, dan tarif.', 'Periksa PPh 21 yang dihitung sistem.', 'Simpan setiap baris nominatif.'], 8.05, 2.3, 4.1, 1.65); note(s, 'Kerahasiaan', 'Pastikan penerima dan rekening sesuai dokumen. Jangan mengisi data fiktif.', 8.05, 4.55, 4.55, 1.15, C.softGold, C.gold); }
{ const s = addSlide('Review dan ajukan permohonan', '15  /  PERMOHONAN DANA', 'Sebelum diajukan, PUMK bertanggung jawab memastikan data telah lengkap dan benar.'); placeholder(s, 'Screenshot review / print preview', 0.65, 1.85, 7.1, 4.55); box(s, 8.05, 1.85, 4.55, 2.55, C.white, C.line); text(s, 'Checklist sebelum submit', 8.35, 2.12, 3.8, 0.25, { fontSize: 14, color: C.navy, bold: true }); bulletList(s, ['Kegiatan dan waktu benar.', 'Dokumen wajib tersedia.', 'Rincian biaya sesuai pagu.', 'Nominatif dan rekening benar.', 'Klik Ajukan lalu konfirmasi.'], 8.35, 2.55, 3.85, 1.4); note(s, 'Status', 'Setelah diajukan, permohonan masuk ke pemeriksaan KA.TIM.', 8.05, 4.75, 4.55, 1.0, C.mint, C.teal); }

section('Persetujuan Berjenjang', 'Setiap pemeriksa menilai permohonan dari sudut pandang kewenangannya.', 'D', C.gold);
{ const s = addSlide('Alur pemeriksaan dan persetujuan', '16  /  PERSETUJUAN', 'Permohonan berpindah ke tahap berikutnya setelah disetujui pada tahap berjalan.'); const steps = [['PUMK', 'Ajukan'], ['KA.TIM', 'Periksa'], ['PIC Keuangan', 'Verifikasi'], ['Pimpinan / Kabag', 'Setujui'], ['PPK', 'Setujui'], ['Bendahara', 'Cairkan']]; steps.forEach((v, i) => { const x = 0.65 + i * 2.05; const color = i === 5 ? C.teal : i === 0 ? C.blue : C.gold; slideNode(s, v[0], v[1], x, 2.55, color); if (i < steps.length - 1) text(s, '›', x + 1.76, 2.8, 0.25, 0.35, { fontSize: 22, color: C.gold, bold: true, align: 'center' }); }); function slideNode(slide, role, action, x, y, color) { slide.addShape(pptx.ShapeType.ellipse, { x, y, w: 1.25, h: 1.25, fill: { color }, line: { color } }); text(slide, role, x + 0.08, y + 0.32, 1.09, 0.3, { fontSize: 10.5, color: C.white, bold: true, align: 'center' }); text(slide, action, x + 0.08, y + 0.67, 1.09, 0.2, { fontSize: 9, color: i18n(action), align: 'center' }); } function i18n() { return 'FFFFFF'; } note(s, 'Jika perlu revisi', 'Pemeriksa mengembalikan permohonan dengan catatan. PUMK memperbaiki data lalu mengajukan ulang.', 0.65, 4.7, 11.95, 1.0, C.softRed, C.red); }
{ const s = addSlide('KA.TIM dan PIC Keuangan', '17  /  PERSETUJUAN', 'Dua tahap ini memastikan permohonan sesuai kebutuhan tim kerja dan ketentuan keuangan.'); placeholder(s, 'Screenshot daftar / detail verifikasi', 0.65, 1.85, 7.1, 4.55); [['KA.TIM', 'Menilai kebutuhan kegiatan, waktu, dokumen, dan kesesuaian tim kerja.'], ['PIC Keuangan', 'Memeriksa kode akun, sisa pagu, rincian biaya, nominatif, dan dokumen.']].forEach((v, i) => { const y = 1.95 + i * 1.55; box(s, 8.05, y, 4.55, 1.2, i === 0 ? C.softGold : C.softBlue, C.line); text(s, v[0], 8.3, y + 0.2, 3.8, 0.25, { fontSize: 14, color: C.navy, bold: true }); text(s, v[1], 8.3, y + 0.55, 3.85, 0.4, { fontSize: 10, color: C.ink, valign: 'top' }); }); note(s, 'Aksi', 'Klik setujui jika sesuai atau tolak/kembalikan dengan catatan yang jelas.', 8.05, 5.15, 4.55, 0.9, C.mint, C.teal); }
{ const s = addSlide('Pimpinan, PPK, dan catatan keputusan', '18  /  PERSETUJUAN', 'Persetujuan akhir memastikan permohonan layak diproses menuju pencairan.'); placeholder(s, 'Screenshot halaman persetujuan pimpinan / PPK', 0.65, 1.85, 7.1, 4.55); text(s, 'Saat memeriksa', 8.05, 1.9, 4.2, 0.25, { fontSize: 14, color: C.navy, bold: true }); bulletList(s, ['Baca ringkasan permohonan.', 'Periksa total anggaran dan tujuan.', 'Periksa catatan dari tahap sebelumnya.', 'Setujui atau kembalikan dengan alasan.'], 8.05, 2.35, 4.1, 1.35); note(s, 'Jejak audit', 'Nama pemeriksa, waktu keputusan, dan catatan tersimpan pada riwayat permohonan.', 8.05, 4.45, 4.55, 1.2, C.softBlue, C.blue); }

section('Pencairan & LPJ', 'Menutup siklus permohonan melalui pencairan, bukti pembayaran, dan pertanggungjawaban.', 'E', C.teal);
{ const s = addSlide('Pencairan oleh Bendahara', '19  /  PENCAIRAN', 'Bendahara memproses permohonan yang telah melewati seluruh tahap persetujuan.'); placeholder(s, 'Screenshot daftar siap dicairkan', 0.65, 1.85, 7.1, 4.55); box(s, 8.05, 1.85, 4.55, 2.55, C.white, C.line); text(s, 'Prosedur', 8.35, 2.12, 3.8, 0.25, { fontSize: 14, color: C.navy, bold: true }); bulletList(s, ['Buka Permohonan Dana sebagai Bendahara.', 'Pilih permohonan siap dicairkan.', 'Periksa nilai dan dokumen persetujuan.', 'Klik Setujui/Cairkan dan konfirmasi.'], 8.35, 2.55, 3.85, 1.35); note(s, 'Hasil', 'Status berubah menjadi Dicairkan dan waktu pencairan tercatat.', 8.05, 4.75, 4.55, 1.0, C.mint, C.teal); }
{ const s = addSlide('Bukti pembayaran dan LPJ', '20  /  PERTANGGUNGJAWABAN', 'Dokumen setelah pencairan menjadi bukti bahwa dana telah direalisasikan dan dipertanggungjawabkan.'); placeholder(s, 'Screenshot unggah bukti bayar / LPJ', 0.65, 1.85, 7.1, 4.55); [['Bukti pembayaran', 'Diunggah oleh Bendahara setelah proses pencairan.'], ['LPJ', 'Diunggah oleh PUMK untuk pertanggungjawaban kegiatan.'], ['Verifikasi LPJ', 'Diperiksa oleh PIC Keuangan atau Bendahara sesuai alur.']].forEach((v, i) => { const y = 1.95 + i * 1.3; pill(s, String(i + 1).padStart(2, '0'), 8.05, y + 0.1, 0.45, i === 1 ? C.mint : C.softBlue, C.navy); text(s, v[0], 8.7, y, 3.55, 0.25, { fontSize: 13, color: C.navy, bold: true }); text(s, v[1], 8.7, y + 0.34, 3.55, 0.35, { fontSize: 10, color: C.muted, valign: 'top' }); }); }
{ const s = addSlide('Status, revisi, dan riwayat', '21  /  MONITORING', 'Pantau posisi permohonan agar tindak lanjut dilakukan oleh pengguna yang tepat.'); const statuses = [['Draft', C.muted], ['Diajukan', C.blue], ['Diverifikasi', C.gold], ['Disetujui', C.teal], ['Dicairkan', '2F855A']]; statuses.forEach((v, i) => { const x = 0.65 + i * 2.38; box(s, x, 2.0, 2.05, 0.78, C.white, C.line); slideDot(s, x + 0.22, 2.28, v[1]); text(s, v[0], x + 0.48, 2.25, 1.35, 0.2, { fontSize: 11, color: C.navy, bold: true }); if (i < statuses.length - 1) text(s, '›', x + 2.1, 2.2, 0.25, 0.3, { fontSize: 20, color: C.gold, bold: true, align: 'center' }); }); function slideDot(slide, x, y, color) { slide.addShape(pptx.ShapeType.ellipse, { x, y, w: 0.18, h: 0.18, fill: { color }, line: { color } }); } placeholder(s, 'Screenshot timeline / riwayat permohonan', 0.65, 3.35, 7.1, 2.7); note(s, 'Revisi', 'Baca catatan penolakan, lakukan perbaikan, lalu ajukan kembali sesuai kewenangan.', 8.05, 3.35, 4.55, 1.15, C.softRed, C.red); note(s, 'Monitoring', 'Gunakan filter status dan buka detail untuk melihat aktor serta waktu setiap keputusan.', 8.05, 4.8, 4.55, 1.15, C.softBlue, C.blue); }

// Closing
{ const s = addSlide('Checklist penggunaan yang aman', '22  /  PENUTUP', 'Gunakan checklist ini sebelum menyelesaikan proses pada setiap tahap.'); const checks = [['Data master', 'Tahun anggaran, pengguna, pegawai, dan tim kerja sudah benar.'], ['Anggaran', 'RKA-K/L sesuai tahun aktif dan rincian biaya memiliki sisa pagu.'], ['Permohonan', 'Kegiatan, dokumen, biaya, dan nominatif telah diperiksa.'], ['Persetujuan', 'Keputusan diberikan sesuai role dan disertai catatan bila perlu.'], ['Pertanggungjawaban', 'Bukti pembayaran dan LPJ diunggah pada permohonan yang benar.'], ['Keamanan', 'Data pribadi dan dokumen internal tidak dibagikan di luar kebutuhan.']]; checks.forEach((v, i) => { const x = 0.65 + (i % 2) * 6.15; const y = 1.8 + Math.floor(i / 2) * 1.25; box(s, x, y, 5.65, 0.92, C.white, C.line); slideDot(s, x + 0.25, y + 0.32, C.teal); text(s, v[0], x + 0.58, y + 0.16, 4.7, 0.22, { fontSize: 12, color: C.navy, bold: true }); text(s, v[1], x + 0.58, y + 0.48, 4.7, 0.25, { fontSize: 9.5, color: C.muted }); }); note(s, 'Bantuan', 'Jika menemukan kendala, catat nomor permohonan, role pengguna, menu, dan pesan error sebelum melapor kepada pengelola SIPITUNG.', 0.65, 5.75, 11.95, 0.75, C.mint, C.teal); function slideDot(slide, x, y, color) { slide.addShape(pptx.ShapeType.ellipse, { x, y, w: 0.18, h: 0.18, fill: { color }, line: { color } }); } }

await pptx.writeFile({ fileName: 'Manual_Book_Modul_Keuangan_SIPITUNG_LLDIKTI_Wilayah_III.pptx' });
